apiVersion: v1
kind: ReplicationController
metadata:
  name: devicectl-edge
  labels:
    communication-layer: devicectl-edge
spec:
  replicas: 1
  selector:
    communication-layer: devicectl-edge
  template:
    metadata:
      labels:
        communication-layer: devicectl-edge
    spec:
      containers:
      - name: devicectl-edge
        image: ${IMG}
        command: ["/usr/bin/java"]
        args: ["-jar", "/jar/ControllerApi.jar", "-l", "debug",
           "-i", "rabbitmq",
           "-r", "iot.devicectl.routing",
           "-t", "direct",
           "-x", "iot.devicectl.exchange"]
---

apiVersion: v1
kind: Service
metadata:
  labels:
    communication-layer: devicectl-edge
  name: devicectl-service
spec:
  #type: NodePort
  ports:
  - port: 8083
    name: port-8083
  selector:
    communication-layer: devicectl-edge
